### ISSUE TITLE
deepgram transcribe quality in livekit much lower than when transcribing on deepgram demo website

### ISSUE THREAD

**Issue by aviadr1** [livekit/agents#202] opened 2024-03-26 00:03 UTC
please compare the transcribing the accuracy of running the livekit+deepgram agent demo with running the deepgram demo on their website, you will see quality of transcription much higher on deepgram.

deepgram demo:
https://console.deepgram.com/project/<YOUR_PROJECT_ID>/mission/transcribe-your-voice-in-realtime

livekit+agent demo:
https://github.com/livekit/agents/tree/main/livekit-plugins/livekit-plugins-deepgram/livekit/plugins/deepgram

**Comment by davidzhao** [comment] 2024-03-26 06:33
which model are you using on the website vs the plugin?

can you share any reproductions of this? without examples or reproductions, it's not clear to us what the issue is.

**Comment by aviadr1** [comment] 2024-03-26 06:41
the deepgram demo uses the defaults for every config and the "nova" model.
the livekit+agent demo uses modified code and configs.

I have been able to get similar performance to the deepgram demo by reverting back to the defaults using this code to replace `livekit.plugins.deepgram.stt.STT` : 

class MySTT(STT):
    def stream(self, *, language: Optional[str] = None) -> "SpeechStream":
        config = self._sanitize_options(language=language)
        return SpeechStream(
            config,
            api_key=self._api_key,
            sample_rate=24000,
        )

    async def _try_connect(self, session: aiohttp.ClientSession) -> aiohttp.ClientWebSocketResponse:
        # TODO: seems like using the default parameters as are available in in the STT demo
        #       https://console.deepgram.com/project/9ea3e34f-5776-47e1-9366-232fa0c5a887/mission/transcribe-your-voice-in-realtime
        #       works better somehow. the github for this is https://github.com/deepgram-devs/js-live-example/blob/main/public/client.js
        #       I'm not sure which of this parameters is the one that is causing the issue.
        #       need to experiment with it.
        live_config = {
            # "model": self._config.model,
            "model": "nova",
            # "punctuate": self._config.punctuate,
            # "smart_format": self._config.smart_format,
            # "interim_results": self._config.interim_results,
            "encoding": "linear16",
            "sample_rate": self._sample_rate,
            "channels": self._num_channels,
            # "endpointing": str(self._config.endpointing or "10"),
        }

        if self._config.language:
            live_config["language"] = self._config.language

        query_params = urlencode(live_config).lower()

        url = f"wss://api.deepgram.com/v1/listen?{query_params}"
        ws = await session.ws_connect(url, headers={"Authorization": f"Token {self._api_key}"})

        return ws

**Comment by davidzhao** [comment] 2024-03-26 06:48
Can you clarify what the issue is? Please provide some examples that succeeds with the parameters that you've posted, but fails with the existing code.

**Comment by jasonison** [comment] 2024-04-12 14:00
I've performed similar tests and agree that the speech recognition quality is better using the deepgram demo on their website. I put 2 browsers, side by side, using a single mic, and there are recognition issues on the livekit/deepgram plugin side. I've traced this to the resample = audio_frame_event.frame.remix_and_resample(16000, 1) routine. After the remix, I wrote to a wav file and the audio has static and I assume is contributing to poor recognition by deepgram. If you remove this resampling and use the 44000 audio channel, it is crystal clear when written to wav file and also when sending this to depgram, it is perfect and the recognition is perfect. I know it is preferable to send at the lower rate but currently from my experience and testing the current resampling is causing quality problems.

**Comment by davidzhao** [comment] 2024-04-14 07:06
great digging here @jasonison! We can confirm as well this is a limitation with our (naive) resampler today. While we work on improving it, removing resampling is the best short-term solution. If you are up for opening a PR, that'd be amazing!

**Comment by vanics** [comment] 2024-04-17 12:20
I am looking forward to this PR.
I am not strong in Python otherwise I'd create myself. :)

**Comment by vanics** [comment] 2024-04-17 13:38
I take it back, it might be as simple as the PR I created below:
https://github.com/livekit/agents/pull/245

I've tested and it works way better. Now it is performing pretty much the same.

**Comment by diogeneshamilton** [comment] 2024-05-07 16:10
I checked this branch out and I'm seeing better performance. Ideally, we have an interface to customize other Deepgram settings as well, like utterance and endpointing.

**Comment by keepingitneil** [comment] 2024-05-14 19:46
Closing this because there is a workaround and we are working on a better re-sampler to handle this issue more generally.

**Closed by keepingitneil** 2024-05-14 19:46 UTC
