### ISSUE TITLE
Re-join the room after agent server restarted

### ISSUE THREAD

**Issue by WqyJh** [livekit/agents#240] opened 2024-04-15 03:59 UTC
Currently, if agent server were restarted, all agents of joined rooms would be disconnected. Is there any way to make the agent re-join the room, or to invite the agent to the room actively?

**Comment by theomonnom** [comment] 2024-04-16 21:09
Hey, this is a duplicate of https://github.com/livekit/agents/issues/242
This is currently in our near term roadmap :)

**Closed by theomonnom** 2024-04-16 21:09 UTC
